---

- hosts: all
  become: true
  tasks:

    - name: Copy default_html file for site
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

